version: '3'

services:
  uas_struktur_data:
    image: mariadb:10.2
    container_name: uas_struktur_data
    restart: unless-stopped
    tty: true
    ports:
      - "31235:3306"
    volumes:
      - ./database/data:/var/lib/mysql
      - ./database/conf.d:/etc/mysql/conf.d:ro
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: uas_123
      MYSQL_ROOT_PASSWORD: uas_123
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    read_only: false

  # phpmyadmin:
  #   image: phpmyadmin:latest
  #   container_name: phpmyadmin
  #   restart: always
  #   ports:
  #     - 9100:80
  #   environment:
  #     - PMA_ARBITRARY=1